apiVersion: v1
kind: Service
metadata:
  name: call-gpt
  labels:
    app: call-gpt
spec:
  selector:
    app: call-gpt
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
